// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:4a52def8-de90-4c35-8760-bfd31e5fc4c2',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'sdms-hosting-mobilehub-381862358',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1pecps1xsqaoz.cloudfront.net',
    'aws_mobile_analytics_app_id': '9c56564b5baf4b59981834a7ca42300b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7ace1f00-3293-11e8-a875-91fe1329a573',
    'aws_project_name': 'SDMS',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'sdms-mobilehub-381862358',
}

export default awsmobile;
